import Aeneas
import NoxVerified

/-!
# The value split the note commitment is built from

Proved about the Rust that ships rather than about a model of it.
`NoxVerified.lean` is generated by Aeneas from `verified/src/limbs.rs`, so the
functions below are the ones the wallet calls.

Everything is machine bounded. `U64` here is a 64 bit bitvector, the shifts are
the checked ones Rust performs and can fail, and nothing is widened to `Nat` to
make the arithmetic easier.
-/

open Aeneas Aeneas.Std Result Aeneas.Std.WP
open NoxVerified

namespace NoxVerified

/-- **Splitting a value into two 32 bit halves and rebuilding it returns what
it started as**, for every one of the 2^64 values a `u64` can hold.

This is the layout two codebases had to compare by hand: the wallet hashes a note's
value as a low limb then a high limb, and the settlement contract recomputes
the same commitment. A disagreement here shows up as every served record being
rejected, on a deployed pool, weeks after anybody looked at this code.

The statement also says the three functions cannot fail, because a Hoare triple
in this form only holds when the monadic code returns `ok`: the shifts are
Rust's checked shifts and 32 is inside the width of a `u64`. -/
@[step]
theorem the_halves_rebuild_the_value (value : U64) :
    (do
      let lo ← limbs.low value
      let hi ← limbs.high value
      limbs.join lo hi) ⦃ result => result = value ⦄ := by
  unfold limbs.low limbs.high limbs.join
  step*
  bv_tac_preprocess 64
  /-
   * Proved through the bits rather than by a SAT call.
   *
   * `bv_tac` closes this in one line, but it calls a solver and then checks
   * the certificate with a reflected checker, which adds a native evaluation
   * axiom to whatever it proves. Going bit by bit keeps the theorem on Lean's
   * own three axioms, and the verify workflow fails if a fourth ever appears.
   *
   * Three ranges of bit index: below 32, where the low half is the value and
   * the shifted half contributes nothing; 32 to 63, where the shifted half is
   * the value and the low half contributes nothing; and 64 up, where a
   * bitvector has no bits and the premise is false.
   -/
  apply BitVec.eq_of_getLsbD_eq
  intro i
  have mask : (4294967295#64 : BitVec 64) = BitVec.ofNat 64 (2 ^ 32 - 1) := by norm_num
  simp only [mask, BitVec.getLsbD_or, BitVec.getLsbD_and, BitVec.getLsbD_shiftLeft,
    BitVec.getLsbD_ushiftRight, BitVec.getLsbD_ofNat, Nat.testBit_two_pow_sub_one]
  rcases Nat.lt_or_ge i 32 with h | h
  · simp [h]
    intro inside _
    exact inside
  · rcases Nat.lt_or_ge i 64 with hw | hw
    · have h1 : ¬ i < 32 := by omega
      have h2 : i - 32 < 32 := by omega
      have h3 : i - 32 < 64 := by omega
      have h4 : 32 + (i - 32) = i := by omega
      simp [h1, h2, h3, h4, hw, BitVec.getLsbD_eq_getElem]
    · intro inside
      omega

end NoxVerified
