-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nox_verified]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace NoxVerified

/-- [nox_verified::amount::SCALE]
    Source: 'src/amount.rs', lines 14:0-14:49
    Visibility: public -/
@[global_simps, irreducible]
def amount.SCALE : Std.U64 := 1000000000000000000#u64

/-- [nox_verified::amount::split]:
    Source: 'src/amount.rs', lines 18:0-20:1
    Visibility: public -/
def amount.split (units : Std.U64) : Result (Std.U64 × Std.U64) := do
  let i ← units / amount.SCALE
  let i1 ← units % amount.SCALE
  ok (i, i1)

/-- [nox_verified::amount::combine]:
    Source: 'src/amount.rs', lines 28:0-40:1
    Visibility: public -/
def amount.combine
  (whole : Std.U64) (fraction : Std.U64) : Result (Option Std.U64) := do
  if fraction >= amount.SCALE
  then ok none
  else
    let o ← lift (U64.checked_mul whole amount.SCALE)
    match o with
    | none => ok none
    | some scaled => ok (U64.checked_add scaled fraction)

/-- [nox_verified::base32::glyph]:
    Source: 'src/base32.rs', lines 9:0-17:1
    Visibility: public -/
def base32.glyph (value : Std.U8) : Result (Option Std.U8) := do
  if value < 26#u8
  then let i ← 97#u8 + value
       ok (some i)
  else
    if value < 32#u8
    then let i ← value - 26#u8
         let i1 ← 50#u8 + i
         ok (some i1)
    else ok none

/-- [nox_verified::base32::value]:
    Source: 'src/base32.rs', lines 20:0-28:1
    Visibility: public -/
def base32.value (glyph : Std.U8) : Result (Option Std.U8) := do
  if glyph >= 97#u8
  then
    if glyph <= 122#u8
    then let i ← glyph - 97#u8
         ok (some i)
    else
      if glyph >= 50#u8
      then
        if glyph <= 55#u8
        then let i ← glyph - 50#u8
             let i1 ← 26#u8 + i
             ok (some i1)
        else ok none
      else ok none
  else
    if glyph >= 50#u8
    then
      if glyph <= 55#u8
      then let i ← glyph - 50#u8
           let i1 ← 26#u8 + i
           ok (some i1)
      else ok none
    else ok none

/-- [nox_verified::base32::encode5]:
    Source: 'src/base32.rs', lines 31:0-42:1
    Visibility: public -/
def base32.encode5
  (b : Array Std.U8 5#usize) : Result (Array Std.U8 8#usize) := do
  let i ← Array.index_usize b 0#usize
  let i1 ← i / 8#u8
  let i2 ← i % 8#u8
  let i3 ← i2 * 4#u8
  let i4 ← Array.index_usize b 1#usize
  let i5 ← i4 / 64#u8
  let i6 ← i3 + i5
  let i7 ← i4 / 2#u8
  let i8 ← i7 % 32#u8
  let i9 ← i4 % 2#u8
  let i10 ← i9 * 16#u8
  let i11 ← Array.index_usize b 2#usize
  let i12 ← i11 / 16#u8
  let i13 ← i10 + i12
  let i14 ← i11 % 16#u8
  let i15 ← i14 * 2#u8
  let i16 ← Array.index_usize b 3#usize
  let i17 ← i16 / 128#u8
  let i18 ← i15 + i17
  let i19 ← i16 / 4#u8
  let i20 ← i19 % 32#u8
  let i21 ← i16 % 4#u8
  let i22 ← i21 * 8#u8
  let i23 ← Array.index_usize b 4#usize
  let i24 ← i23 / 32#u8
  let i25 ← i22 + i24
  let i26 ← i23 % 32#u8
  ok (Array.make 8#usize [ i1, i6, i8, i13, i18, i20, i25, i26 ])

/-- [nox_verified::base32::decode5]:
    Source: 'src/base32.rs', lines 45:0-59:1
    Visibility: public -/
def base32.decode5
  (s : Array Std.U8 8#usize) : Result (Option (Array Std.U8 5#usize)) := do
  let i ← Array.index_usize s 0#usize
  if i >= 32#u8
  then ok none
  else
    let i1 ← Array.index_usize s 1#usize
    if i1 >= 32#u8
    then ok none
    else
      let i2 ← Array.index_usize s 2#usize
      if i2 >= 32#u8
      then ok none
      else
        let i3 ← Array.index_usize s 3#usize
        if i3 >= 32#u8
        then ok none
        else
          let i4 ← Array.index_usize s 4#usize
          if i4 >= 32#u8
          then ok none
          else
            let i5 ← Array.index_usize s 5#usize
            if i5 >= 32#u8
            then ok none
            else
              let i6 ← Array.index_usize s 6#usize
              if i6 >= 32#u8
              then ok none
              else
                let i7 ← Array.index_usize s 7#usize
                if i7 >= 32#u8
                then ok none
                else
                  let i8 ← i * 8#u8
                  let i9 ← i1 / 4#u8
                  let i10 ← i8 + i9
                  let i11 ← i1 % 4#u8
                  let i12 ← i11 * 64#u8
                  let i13 ← i2 * 2#u8
                  let i14 ← i12 + i13
                  let i15 ← i3 / 16#u8
                  let i16 ← i14 + i15
                  let i17 ← i3 % 16#u8
                  let i18 ← i17 * 16#u8
                  let i19 ← i4 / 2#u8
                  let i20 ← i18 + i19
                  let i21 ← i4 % 2#u8
                  let i22 ← i21 * 128#u8
                  let i23 ← i5 * 4#u8
                  let i24 ← i22 + i23
                  let i25 ← i6 / 8#u8
                  let i26 ← i24 + i25
                  let i27 ← i6 % 8#u8
                  let i28 ← i27 * 32#u8
                  let i29 ← i28 + i7
                  ok (some (Array.make 5#usize [ i10, i16, i20, i26, i29 ]))

/-- [nox_verified::base32_tail::encode3]:
    Source: 'src/base32_tail.rs', lines 12:0-20:1
    Visibility: public -/
def base32_tail.encode3
  (b : Array Std.U8 3#usize) : Result (Array Std.U8 5#usize) := do
  let i ← Array.index_usize b 0#usize
  let i1 ← i / 8#u8
  let i2 ← i % 8#u8
  let i3 ← i2 * 4#u8
  let i4 ← Array.index_usize b 1#usize
  let i5 ← i4 / 64#u8
  let i6 ← i3 + i5
  let i7 ← i4 / 2#u8
  let i8 ← i7 % 32#u8
  let i9 ← i4 % 2#u8
  let i10 ← i9 * 16#u8
  let i11 ← Array.index_usize b 2#usize
  let i12 ← i11 / 16#u8
  let i13 ← i10 + i12
  let i14 ← i11 % 16#u8
  let i15 ← i14 * 2#u8
  ok (Array.make 5#usize [ i1, i6, i8, i13, i15 ])

/-- [nox_verified::base32_tail::decode3]:
    Source: 'src/base32_tail.rs', lines 24:0-32:1
    Visibility: public -/
def base32_tail.decode3
  (s : Array Std.U8 5#usize) : Result (Option (Array Std.U8 3#usize)) := do
  let i ← Array.index_usize s 0#usize
  if i >= 32#u8
  then ok none
  else
    let i1 ← Array.index_usize s 1#usize
    if i1 >= 32#u8
    then ok none
    else
      let i2 ← Array.index_usize s 2#usize
      if i2 >= 32#u8
      then ok none
      else
        let i3 ← Array.index_usize s 3#usize
        if i3 >= 32#u8
        then ok none
        else
          let i4 ← Array.index_usize s 4#usize
          if i4 >= 32#u8
          then ok none
          else
            let i5 ← i4 % 2#u8
            if i5 != 0#u8
            then ok none
            else
              let i6 ← i * 8#u8
              let i7 ← i1 / 4#u8
              let i8 ← i6 + i7
              let i9 ← i1 % 4#u8
              let i10 ← i9 * 64#u8
              let i11 ← i2 * 2#u8
              let i12 ← i10 + i11
              let i13 ← i3 / 16#u8
              let i14 ← i12 + i13
              let i15 ← i3 % 16#u8
              let i16 ← i15 * 16#u8
              let i17 ← i4 / 2#u8
              let i18 ← i16 + i17
              ok (some (Array.make 3#usize [ i8, i14, i18 ]))

/-- [nox_verified::fee::BPS]
    Source: 'src/fee.rs', lines 5:0-5:29
    Visibility: public -/
@[global_simps, irreducible] def fee.BPS : Std.U128 := 10000#u128

/-- [nox_verified::fee::CEILING]
    Source: 'src/fee.rs', lines 6:0-6:44
    Visibility: public -/
@[global_simps, irreducible] def fee.CEILING : Std.U128 := 1000000000000#u128

/-- [nox_verified::fee::MAX_TIP]
    Source: 'src/fee.rs', lines 7:0-7:40
    Visibility: public -/
@[global_simps, irreducible] def fee.MAX_TIP : Std.U128 := 5000000000#u128

/-- [nox_verified::fee::split_fee]:
    Source: 'src/fee.rs', lines 10:0-26:1
    Visibility: public -/
def fee.split_fee
  (amount : Std.U128) (bps : Std.U16) :
  Result (Option (Std.U128 × Std.U128))
  := do
  let i ← lift (UScalar.cast .U128 bps)
  let o ← lift (U128.checked_mul amount i)
  match o with
  | none => ok none
  | some product =>
    let fee ← product / fee.BPS
    if fee < amount
    then
      let o1 ← lift (U128.checked_sub amount fee)
      match o1 with
      | none => ok none
      | some arrives => ok (some (arrives, fee))
    else ok none

/-- [nox_verified::fee::offer]:
    Source: 'src/fee.rs', lines 29:0-44:1
    Visibility: public -/
def fee.offer
  (base : Std.U128) (suggested : Std.U128) :
  Result (Option (Std.U128 × Std.U128))
  := do
  let tip ← if suggested < fee.MAX_TIP
              then ok suggested
              else ok fee.MAX_TIP
  let o ← lift (U128.checked_mul base 2#u128)
  match o with
  | none => ok none
  | some doubled =>
    let o1 ← lift (U128.checked_add doubled tip)
    match o1 with
    | none => ok none
    | some cap => if cap <= fee.CEILING
                  then ok (some (tip, cap))
                  else ok none

/-- [nox_verified::fee::next_nonce]:
    Source: 'src/fee.rs', lines 47:0-53:1
    Visibility: public -/
def fee.next_nonce
  (pending : Std.U64) (recorded : Std.U64) : Result Std.U64 := do
  if pending < recorded
  then ok recorded
  else ok pending

/-- [nox_verified::fee::covers]:
    Source: 'src/fee.rs', lines 56:0-61:1
    Visibility: public -/
def fee.covers
  (balance : Std.U128) (amount : Std.U128) (fee : Std.U128) : Result Bool := do
  let o ← lift (U128.checked_add amount fee)
  match o with
  | none => ok false
  | some need => ok (need <= balance)

/-- [nox_verified::limbs::low]:
    Source: 'src/limbs.rs', lines 14:0-16:1
    Visibility: public -/
def limbs.low (value : Std.U64) : Result Std.U64 := do
  ok (value &&& 4294967295#u64)

/-- [nox_verified::limbs::high]:
    Source: 'src/limbs.rs', lines 19:0-21:1
    Visibility: public -/
def limbs.high (value : Std.U64) : Result Std.U64 := do
  value >>> 32#i32

/-- [nox_verified::limbs::join]:
    Source: 'src/limbs.rs', lines 28:0-30:1
    Visibility: public -/
def limbs.join (low : Std.U64) (high : Std.U64) : Result Std.U64 := do
  let i ← lift (high &&& 4294967295#u64)
  let i1 ← i <<< 32#i32
  let i2 ← lift (low &&& 4294967295#u64)
  ok (i1 ||| i2)

/-- [nox_verified::transfer::balance]:
    Source: 'src/transfer.rs', lines 15:0-28:1
    Visibility: public -/
def transfer.balance
  (first : Std.U64) (second : Std.U64) (amount : Std.U64) (fee : Std.U64) :
  Result (Option (Std.U64 × Std.U64))
  := do
  let o ← lift (U64.checked_add amount fee)
  match o with
  | none => ok none
  | some needed =>
    let o1 ← lift (U64.checked_add first second)
    match o1 with
    | none => ok none
    | some total =>
      let o2 ← lift (U64.checked_sub total needed)
      match o2 with
      | none => ok none
      | some change => ok (some (needed, change))

end NoxVerified
